# Generated by Django 4.0.6 on 2022-07-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=100)),
                ('completado', models.BooleanField()),
                ('pagado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Clienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_Responsable', models.CharField(max_length=20)),
                ('nombre_Responsable', models.CharField(max_length=20)),
                ('apellido_Responsable', models.CharField(max_length=20)),
                ('email_Responsable', models.EmailField(default='name@yahoo.com', max_length=30)),
                ('movil_Responsable', models.IntegerField(default=234567890)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('asignatura_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academiapp.asignatura')),
                ('clienta_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academiapp.clienta')),
            ],
        ),
    ]
